package Artikelverwaltung.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import Artikelverwaltung.Controller.Controller;
import Artikelverwaltung.Controller.MainController;
import Artikelverwaltung.Modell.AArticle;
import DAO.DAOText;
import DAO.IDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nils
 */
public class ViewMain extends javax.swing.JFrame implements ActionListener{

	private MainController mainCon;
	
    /**
     * Creates new form View
     */
    public ViewMain() {
    	this.mainCon = new MainController(this, this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setVisible(true);
    	this.setTitle("Artikelverwaltung");
        searchButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        editButton = new javax.swing.JButton();
        editButton.addActionListener(new ActionListener() {	
			@Override
			public void actionPerformed(ActionEvent e) {
				mainCon.editButtonClicked(e);		
			}
		});

        searchButton.setText("Search");
        searchButton.addActionListener(new ActionListener() {	
			@Override
			public void actionPerformed(ActionEvent e) {
				// mainCon.searchButtonClicked(e);	
				searchTable(searchField.getText());
			}
		});

        createButton.setText("Create");
        createButton.addActionListener(new ActionListener() {	
			@Override
			public void actionPerformed(ActionEvent e) {
				mainCon.createButtonClicked(e);	
			}
		});

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new ActionListener() {	
			@Override
			public void actionPerformed(ActionEvent e) {
				int row = jTable1.getSelectedRow();
				System.out.println(row);
				try {
					String articleNr = jTable1.getValueAt(row, 0).toString();
					mainCon.deleteButtonClicked(e, articleNr);
					refreshTable();
				}
				catch(Exception ex)
				{
					System.out.println("Lern zu klicken.");
				}
			}
		});

        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            	
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                
            },
            new String [] {
                "ArticleNR", "Name", "Amount", "PriceBuy", "PriceSell"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        refreshTable();
        
        jScrollPane1.setViewportView(jTable1);

        editButton.setText("Edit");
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addGap(95, 95, 95)
                .addComponent(createButton)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton)
                    .addComponent(createButton))
                .addContainerGap())
        );

        pack();
      
    }// </editor-fold>//GEN-END:initComponents

    public void refreshTable() {

		for(int i = 0; i < this.jTable1.getRowCount(); i++) {
			jTable1.setValueAt("", i, 0);
			jTable1.setValueAt("", i, 1);
			jTable1.setValueAt("", i, 2);
			jTable1.setValueAt("", i, 3);
			jTable1.setValueAt("", i, 4);
		}
		
		int i = 0;
        for (AArticle element : this.mainCon.getData()) {
        	jTable1.setValueAt(element.getArticleNr(), i, 0);
        	jTable1.setValueAt(element.getName(), i, 1);
        	jTable1.setValueAt(element.getAmount(), i, 2);
        	jTable1.setValueAt(element.getPriceBuy(), i, 3);
        	jTable1.setValueAt(element.getPriceSell(), i, 4);
        	i++;
		}
	}
    
    
    private void searchTable(String searchText) {
    	
    	jTable1.clearSelection();
    	
		for(int i = 0; i < this.jTable1.getRowCount(); i++) {
			String result = jTable1.getValueAt(i, 0).toString();
			
			if(result.contains(searchText)) {
				jTable1.setRowSelectionInterval(i, i);
				break;
			}			
		}
		System.out.println("Leider ist die McFlurry-Maschine gerade kaputt.");
	}
	

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
	}
	
	
}
